"""Coaching modality catalog.

Layered on purpose (domain / approach / session model / tool / delivery) so a coach can
practise several modalities at once and get a concrete resource kit for each one.
Nothing here is medical, legal or regulated advice: every domain carries scope
exclusions and escalation routes that the product must respect.
"""

GROUPS: list[dict] = [
    {
        "key": "personal",
        "label": "Personal Development and Life Direction",
        "blurb": "Clarity, habits, confidence and navigating change.",
    },
    {
        "key": "career",
        "label": "Career, Leadership and Workplace",
        "blurb": "Work direction, hiring, leading people and running a business.",
    },
    {
        "key": "health",
        "label": "Health, Wellness and Performance",
        "blurb": "Self-directed lifestyle change, training, recovery and performance.",
        "safety": (
            "Client-centred and non-clinical only: no diagnosing, interpreting medical data, "
            "prescribing or de-prescribing, supplement advice, meal plans or therapy."
        ),
    },
    {
        "key": "relationships",
        "label": "Relationships, Family and Social Life",
        "blurb": "Communication, repair, parenting and social confidence.",
        "safety": (
            "Screen for coercion, violence, stalking and retaliation risk. Better communication "
            "is never the default answer in an unsafe situation."
        ),
    },
    {
        "key": "specialized",
        "label": "Identity, Inclusion and Specialised Contexts",
        "blurb": "Values, belonging, neurodiversity, caregiving, loss and relocation.",
        "safety": "Be explicit about coaching versus peer support, education or licensed care.",
    },
]

APPROACHES: list[dict] = [
    {"key": "motivational_interviewing", "label": "Motivational interviewing",
     "contributes": "Explores ambivalence and elicits the client's own reasons for change.",
     "config": "Reflective listening, permission before advice, readiness scaling, autonomy-supportive language."},
    {"key": "solution_focused", "label": "Solution-focused",
     "contributes": "Focuses on the preferred future, exceptions and the next useful step.",
     "config": "Preferred-future prompt, exception finder, scaling question, small-step generator."},
    {"key": "strengths_based", "label": "Strengths-based",
     "contributes": "Builds on capabilities, assets and past successes.",
     "config": "Strength inventory, evidence capture, strengths-in-context prompts."},
    {"key": "positive_psychology", "label": "Positive psychology",
     "contributes": "Uses values, gratitude, hope and well-being practices.",
     "config": "Exercise library, dosage and frequency controls, outcome reflection."},
    {"key": "cognitive_behavioural", "label": "Cognitive-behavioural coaching",
     "contributes": "Links situations, thoughts, emotions, behaviours and experiments.",
     "config": "Thought record, behavioural experiment, reframes. Never presented as therapy."},
    {"key": "act_informed", "label": "Acceptance and commitment informed",
     "contributes": "Supports values-guided action alongside difficult internal experiences.",
     "config": "Defusion language, values action, willingness reflection, refer out when treatment is indicated."},
    {"key": "mindfulness_informed", "label": "Mindfulness informed",
     "contributes": "Present-moment awareness and non-reactive reflection.",
     "config": "Short practices, sensory options, secular or faith-sensitive language."},
    {"key": "somatic", "label": "Somatic and body-aware",
     "contributes": "Includes sensation, posture and energy in the work.",
     "config": "Consent-based body check-ins, opt-out, accessible alternatives, no medical interpretation."},
    {"key": "narrative", "label": "Narrative",
     "contributes": "Examines the stories and identities shaping action.",
     "config": "Externalisation prompts, re-authoring, evidence of preferred identity."},
    {"key": "systems", "label": "Systems",
     "contributes": "Considers relationships, roles, incentives and structural context.",
     "config": "Stakeholder map, feedback loops, unintended-consequence prompts."},
    {"key": "person_centered", "label": "Person-centred and co-active",
     "contributes": "Partnership, presence, listening and the client's agenda.",
     "config": "Client-led agenda, reflective summaries, permission-based challenge."},
    {"key": "trauma_informed", "label": "Trauma informed",
     "contributes": "Safety, choice, empowerment and collaboration without coercive probing.",
     "config": "Consent gates, grounding, opt-out, non-graphic prompts, crisis routing."},
    {"key": "accountability", "label": "Accountability",
     "contributes": "Makes commitments visible with predictable review cycles.",
     "config": "Commitment ledger, reminders, accountability partner, non-punitive reset."},
    {"key": "peer", "label": "Peer coaching",
     "contributes": "Reciprocal support and shared experience.",
     "config": "Matching, group norms, moderation, anonymised sharing."},
    {"key": "mentoring_informed", "label": "Mentoring informed",
     "contributes": "Bounded expertise and examples when the client wants them.",
     "config": "Explicit coach-versus-mentor mode switch, disclosure of experience."},
]

SESSION_MODELS: list[dict] = [
    {"key": "grow", "label": "GROW", "use": "Goal clarification and action planning",
     "fields": ["Goal", "Reality", "Options", "Way forward"],
     "output": "Goal statement, options, selected action, review date"},
    {"key": "smart", "label": "SMART", "use": "Making outcomes specific and observable",
     "fields": ["Specific", "Measure", "Baseline", "Target", "Deadline"],
     "output": "Measurable goal card"},
    {"key": "woop", "label": "WOOP", "use": "Turning wishes into plans that anticipate obstacles",
     "fields": ["Wish", "Outcome", "Obstacle", "Plan"],
     "output": "If-then plan and obstacle response"},
    {"key": "clear", "label": "CLEAR", "use": "Longer conversations with contracting and review",
     "fields": ["Contract", "Listen", "Explore", "Action", "Review"],
     "output": "Session summary and commitment"},
    {"key": "fuel", "label": "FUEL", "use": "Workplace and performance conversations",
     "fields": ["Frame", "Understand", "Explore", "Lay out next steps"],
     "output": "Conversation agenda and commitments"},
    {"key": "oskar", "label": "OSKAR", "use": "Solution-focused progress reviews",
     "fields": ["Outcome", "Scaling", "Know-how", "Affirm", "Review"],
     "output": "Progress score, resources, next action"},
    {"key": "wheel_of_life", "label": "Wheel of Life", "use": "Broad intake and prioritisation",
     "fields": ["Life areas", "Score each area", "Chosen focus"],
     "output": "Visual priorities and selected focus area"},
    {"key": "values_sort", "label": "Values sort", "use": "Clarifying priorities and trade-offs",
     "fields": ["Top values", "Conflicts", "Non-negotiables"],
     "output": "Ranked values and alignment gaps"},
    {"key": "habit_loop", "label": "Habit loop", "use": "Cue, routine, reward and environment design",
     "fields": ["Cue", "Behaviour", "Reward", "Friction"],
     "output": "Experiment and tracking plan"},
    {"key": "implementation_intention", "label": "Implementation intention", "use": "Increasing follow-through",
     "fields": ["If (cue)", "Then (action)", "Where", "When", "Backup"],
     "output": "If-then commitment"},
    {"key": "after_action_review", "label": "After-action review", "use": "Learning from performance or setbacks",
     "fields": ["Intended result", "Actual result", "Causes", "Learning", "Next change"],
     "output": "Learning record and revised plan"},
    {"key": "pre_mortem", "label": "Pre-mortem", "use": "Decision and project risk identification",
     "fields": ["Decision", "How it could fail", "Early signals", "Mitigations"],
     "output": "Risk register and mitigations"},
    {"key": "check_in_scales", "label": "Check-in scales", "use": "Readiness, confidence, energy, stress or progress",
     "fields": ["Scale 1-10", "What moved it", "Next smallest step"],
     "output": "Trend plus a coaching question"},
]

# domain: key, group, label, offering, must_have, inputs, outputs, approaches,
#         models, exclusions, escalation, intake (lead-form questions), checkin (questions)
DOMAINS: list[dict] = [
    # ---------------- personal ----------------
    {"key": "life", "group": "personal", "label": "Life coaching",
     "offering": "A flexible personal-goals programme spanning priorities, transitions, confidence and routines",
     "must_have": "A goal portfolio that stops competing goals overwhelming the client",
     "inputs": ["Life areas", "Current constraints", "Values", "Energy", "Time available", "Preferred pace"],
     "outputs": ["Prioritised goals", "Weekly experiments", "Reflection prompts", "Decision log", "Progress narrative"],
     "approaches": ["person_centered", "solution_focused", "accountability"],
     "models": ["wheel_of_life", "grow", "smart"],
     "exclusions": ["Therapy for diagnosed conditions", "Medical or legal advice"],
     "escalation": ["Licensed therapist", "Specialist coach"],
     "intake": ["What do you most want to change in the next 90 days?", "What have you already tried?", "What would make this feel like a win?"],
     "checkin": ["Which goal moved this week?", "What got in the way?", "Confidence 1-10", "Next smallest step"]},
    {"key": "personal_development", "group": "personal", "label": "Personal development coaching",
     "offering": "Structured self-awareness and growth pathways",
     "must_have": "A baseline-to-growth assessment with observable skill targets",
     "inputs": ["Strengths", "Development areas", "Feedback received", "Learning style", "Target timeframe"],
     "outputs": ["Growth plan", "Practice exercises", "Evidence log", "Review summary"],
     "approaches": ["strengths_based", "positive_psychology", "person_centered"],
     "models": ["smart", "after_action_review"],
     "exclusions": ["Psychometric interpretation without qualification"],
     "escalation": ["Assessment-qualified practitioner", "Mentor"],
     "intake": ["Which skill do you want to be visibly better at?", "How would others notice the change?"],
     "checkin": ["What did you practise?", "What evidence of progress did you see?", "Confidence 1-10"]},
    {"key": "purpose", "group": "personal", "label": "Purpose and meaning coaching",
     "offering": "Values, meaning, contribution and life direction exploration",
     "must_have": "Guided values clarification connected to real-world experiments",
     "inputs": ["Values", "Formative experiences", "Sources of meaning", "Trade-offs", "Worldview preferences"],
     "outputs": ["Purpose draft", "Aligned experiments", "Not-now list", "Meaning reflections"],
     "approaches": ["narrative", "act_informed", "person_centered"],
     "models": ["values_sort", "grow"],
     "exclusions": ["Spiritual direction unless requested", "Existential crisis care"],
     "escalation": ["Therapist", "Chaplain or chosen mentor"],
     "intake": ["When do you feel most like yourself?", "What would you regret not doing?"],
     "checkin": ["Which action felt aligned?", "Which felt off?", "Alignment 1-10"]},
    {"key": "confidence", "group": "personal", "label": "Confidence and self-belief coaching",
     "offering": "Practice-oriented confidence building for a defined situation",
     "must_have": "A graded practice ladder with evidence capture",
     "inputs": ["Trigger situations", "Confidence rating", "Feared outcomes", "Past successes", "Support network"],
     "outputs": ["Micro-challenges", "Reappraisal prompts", "Wins log", "Confidence trend"],
     "approaches": ["cognitive_behavioural", "strengths_based", "trauma_informed"],
     "models": ["check_in_scales", "implementation_intention"],
     "exclusions": ["Treatment for anxiety disorders"],
     "escalation": ["Therapist for clinical anxiety"],
     "intake": ["Where does confidence drop the most?", "What would confident look like there?"],
     "checkin": ["Which challenge did you take?", "What happened?", "Confidence 1-10"]},
    {"key": "mindset", "group": "personal", "label": "Mindset coaching",
     "offering": "Identify unhelpful interpretations and test more useful alternatives",
     "must_have": "A thought-to-action loop that avoids simplistic positive thinking",
     "inputs": ["Situation", "Interpretation", "Emotion", "Behaviour", "Alternative view"],
     "outputs": ["Reframes", "Behavioural experiments", "Implementation plan", "Learning review"],
     "approaches": ["cognitive_behavioural", "act_informed"],
     "models": ["after_action_review", "implementation_intention"],
     "exclusions": ["Therapy", "Diagnostic labels"],
     "escalation": ["Therapist"],
     "intake": ["What story do you tell yourself when it gets hard?"],
     "checkin": ["Which reframe did you use?", "What did it change?"]},
    {"key": "resilience", "group": "personal", "label": "Resilience coaching",
     "offering": "Preparation and recovery support for stress, setbacks and uncertainty",
     "must_have": "A resilience plan with early-warning signals and recovery actions",
     "inputs": ["Stressors", "Coping resources", "Sleep and energy", "Social support", "Boundaries"],
     "outputs": ["Coping menu", "Recovery protocol", "Trigger plan", "After-action reflection"],
     "approaches": ["trauma_informed", "mindfulness_informed", "systems"],
     "models": ["check_in_scales", "after_action_review"],
     "exclusions": ["Burnout treatment", "Trauma therapy"],
     "escalation": ["Therapist", "Occupational health"],
     "intake": ["What are your earliest signs of overload?", "What restores you fastest?"],
     "checkin": ["Stress 1-10", "Which recovery action did you use?", "What needs adjusting?"]},
    {"key": "transition", "group": "personal", "label": "Transition and change coaching",
     "offering": "Support through relocation, identity change, separation or major life events",
     "must_have": "A transition map combining emotional processing with practical steps",
     "inputs": ["Change timeline", "Losses and gains", "Uncertainties", "Responsibilities", "Resources"],
     "outputs": ["Transition milestones", "Options map", "Support requests", "Weekly stabilisers"],
     "approaches": ["narrative", "person_centered", "trauma_informed"],
     "models": ["grow", "pre_mortem"],
     "exclusions": ["Legal, immigration or financial advice"],
     "escalation": ["Solicitor or specialist adviser", "Therapist"],
     "intake": ["What is changing and by when?", "What feels most unstable?"],
     "checkin": ["What stabilised this week?", "What still feels loose?"]},
    {"key": "decision", "group": "personal", "label": "Decision coaching",
     "offering": "Neutral support for complex personal or professional choices",
     "must_have": "A workspace separating facts, values, uncertainty and reversibility",
     "inputs": ["Options", "Criteria and weights", "Constraints", "Unknowns", "Stakeholders", "Deadline"],
     "outputs": ["Comparison matrix", "Clarifying questions", "Pre-mortem", "Decision record", "Follow-up review"],
     "approaches": ["systems", "person_centered"],
     "models": ["pre_mortem", "grow"],
     "exclusions": ["Recommending the choice for the client", "Regulated advice"],
     "escalation": ["Domain specialist"],
     "intake": ["What decision are you facing and by when?", "What matters most in it?"],
     "checkin": ["What new information arrived?", "Has the leading option changed?"]},
    {"key": "time_productivity", "group": "personal", "label": "Time and productivity coaching",
     "offering": "Planning, prioritisation, focus and sustainable execution",
     "must_have": "Calendar-aware planning tied to energy and capacity, not task volume",
     "inputs": ["Calendar", "Task inventory", "Priorities", "Energy patterns", "Interruptions"],
     "outputs": ["Weekly plan", "Focus blocks", "Next actions", "Bottleneck diagnosis"],
     "approaches": ["accountability", "solution_focused"],
     "models": ["implementation_intention", "check_in_scales"],
     "exclusions": ["ADHD assessment"],
     "escalation": ["ADHD or executive-function specialist"],
     "intake": ["Where does your week fall apart?", "What must not slip?"],
     "checkin": ["Planned versus actual", "Biggest time leak", "Next week's one change"]},
    {"key": "organization", "group": "personal", "label": "Organisation and decluttering coaching",
     "offering": "Reduce physical or digital friction through staged projects",
     "must_have": "Inventory plus a one-zone-at-a-time action flow",
     "inputs": ["Space or system", "Categories", "Emotional difficulty", "Time available", "Disposal constraints"],
     "outputs": ["Decluttering plan", "Batches", "Maintenance routine", "Completion log"],
     "approaches": ["accountability", "solution_focused"],
     "models": ["habit_loop", "implementation_intention"],
     "exclusions": ["Hoarding disorder treatment"],
     "escalation": ["Clinician for hoarding-related distress"],
     "intake": ["Which single zone would change your day?", "How much time can you give it weekly?"],
     "checkin": ["Which zone did you finish?", "What is the maintenance step?"]},

    # ---------------- career ----------------
    {"key": "career", "group": "career", "label": "Career coaching",
     "offering": "Exploration, positioning and career-transition programmes",
     "must_have": "A skills-and-evidence map connected to target roles",
     "inputs": ["Work history", "Skills", "Interests", "Values", "Constraints", "Target roles"],
     "outputs": ["Role hypotheses", "Skills-gap map", "Experiments", "Action queue", "Progress dashboard"],
     "approaches": ["strengths_based", "solution_focused", "person_centered"],
     "models": ["grow", "smart"],
     "exclusions": ["Guaranteed placement", "Legal or immigration advice"],
     "escalation": ["Career counsellor", "Immigration adviser"],
     "intake": ["What roles are you drawn to?", "What must the next role give you?", "What are your hard constraints?"],
     "checkin": ["Which experiment did you run?", "What did you learn about the target role?"]},
    {"key": "job_search", "group": "career", "label": "Job-search coaching",
     "offering": "A time-boxed application and networking system",
     "must_have": "Role-to-evidence matching with human review, never guarantees",
     "inputs": ["CV", "Target postings", "Work authorisation", "Geography", "Networking comfort"],
     "outputs": ["Tailored accomplishment bullets", "Outreach drafts", "Interview plan", "Pipeline tracker"],
     "approaches": ["accountability", "solution_focused"],
     "models": ["smart", "check_in_scales"],
     "exclusions": ["Fabricating experience", "Employment law advice"],
     "escalation": ["Employment solicitor", "Recruiter"],
     "intake": ["How many hours a week can you give the search?", "Which three companies are top of the list?"],
     "checkin": ["Applications sent", "Conversations had", "What needs changing in the pitch?"]},
    {"key": "interview", "group": "career", "label": "Interview coaching",
     "offering": "Practice interviews with role-specific feedback",
     "must_have": "Realistic simulation plus rubric-based feedback",
     "inputs": ["Role", "Level", "Company context", "Competency rubric", "Previous answers"],
     "outputs": ["Transcript", "Scorecard", "Concise feedback", "Improved answer outline", "Practice plan"],
     "approaches": ["mentoring_informed", "accountability"],
     "models": ["after_action_review", "fuel"],
     "exclusions": ["Guaranteeing an offer"],
     "escalation": ["Domain expert for technical screens"],
     "intake": ["Which interview and when?", "Which question worries you most?"],
     "checkin": ["Which answers improved?", "Which still feel weak?"]},
    {"key": "leadership", "group": "career", "label": "Leadership coaching",
     "offering": "Private development for managers and emerging leaders",
     "must_have": "Stakeholder-aware experiments with feedback collection",
     "inputs": ["Role", "Team size", "Leadership goals", "360 feedback", "Organisational context"],
     "outputs": ["Behaviour experiments", "Conversation plans", "Stakeholder map", "Feedback summary"],
     "approaches": ["systems", "person_centered", "strengths_based"],
     "models": ["clear", "fuel", "after_action_review"],
     "exclusions": ["HR investigations", "Legal advice"],
     "escalation": ["HR partner", "Employment solicitor"],
     "intake": ["What would your team say you should do more of?", "Which relationship needs work?"],
     "checkin": ["Which behaviour did you practise?", "What feedback did you gather?"]},
    {"key": "executive", "group": "career", "label": "Executive coaching",
     "offering": "Confidential, sponsor-aware leadership and decision support",
     "must_have": "Client-private space kept separate from sponsor-visible outcomes",
     "inputs": ["Sponsor agreement", "Strategic priorities", "Stakeholder context", "Confidentiality rules"],
     "outputs": ["Leadership goals", "Themes", "Commitments", "Consented sponsor report"],
     "approaches": ["systems", "person_centered"],
     "models": ["clear", "pre_mortem"],
     "exclusions": ["Reporting private content to a sponsor", "Board-level legal advice"],
     "escalation": ["Legal counsel", "Board adviser"],
     "intake": ["What does the sponsor expect?", "What stays private?", "What is the strategic priority?"],
     "checkin": ["Which commitment moved?", "What is the theme to report in aggregate?"]},
    {"key": "manager", "group": "career", "label": "Manager coaching",
     "offering": "Just-in-time support for one-to-ones, delegation and performance",
     "must_have": "Situation-to-conversation planner with role-play",
     "inputs": ["Employee context", "Performance facts", "Desired outcome", "Policy constraints"],
     "outputs": ["Conversation agenda", "Questions", "Neutral language", "Follow-up commitments"],
     "approaches": ["mentoring_informed", "systems"],
     "models": ["fuel", "grow"],
     "exclusions": ["Disciplinary or dismissal advice"],
     "escalation": ["HR partner", "Employment solicitor"],
     "intake": ["Which conversation is coming up?", "What outcome do you want?"],
     "checkin": ["How did the conversation go?", "What did you commit to?"]},
    {"key": "team", "group": "career", "label": "Team coaching",
     "offering": "Team alignment, trust, decision quality and execution",
     "must_have": "Shared goals with psychological-safety-aware facilitation",
     "inputs": ["Team charter", "Roles", "Goals", "Meeting cadence", "Anonymous pulse data"],
     "outputs": ["Team agreements", "Decision log", "Action register", "Aggregate pulse trends"],
     "approaches": ["systems", "peer", "person_centered"],
     "models": ["clear", "oskar", "after_action_review"],
     "exclusions": ["Exposing individual pulse responses", "Grievance handling"],
     "escalation": ["HR partner", "Mediator"],
     "intake": ["What must this team achieve together?", "Where does it get stuck?"],
     "checkin": ["Which agreement held?", "Which action slipped and why?"]},
    {"key": "communication", "group": "career", "label": "Communication and presentation coaching",
     "offering": "Practice for difficult conversations, speaking and concise writing",
     "must_have": "Scenario role-play with selectable audience and stakes",
     "inputs": ["Audience", "Medium", "Objective", "Tone", "Draft content"],
     "outputs": ["Talk track", "Message map", "Rehearsal feedback", "Shorter clearer version"],
     "approaches": ["mentoring_informed", "solution_focused"],
     "models": ["fuel", "after_action_review"],
     "exclusions": ["Writing content the client will present as unaided work in an assessment"],
     "escalation": ["Speech and language professional"],
     "intake": ["What is the message and who is the audience?", "What is at stake?"],
     "checkin": ["How did it land?", "What would you change next time?"]},
    {"key": "entrepreneurship", "group": "career", "label": "Entrepreneurship and business coaching",
     "offering": "Founder clarity, customer discovery, operating rhythm and accountability",
     "must_have": "Milestone dashboard that separates assumptions from evidence",
     "inputs": ["Business stage", "Customer", "Model", "Runway", "Team", "Current hypothesis"],
     "outputs": ["Experiment backlog", "Milestone plan", "KPI definitions", "Decision log", "Weekly review"],
     "approaches": ["accountability", "systems", "solution_focused"],
     "models": ["smart", "pre_mortem", "oskar"],
     "exclusions": ["Investment, tax or legal advice", "Revenue guarantees"],
     "escalation": ["Accountant", "Solicitor", "Sector specialist"],
     "intake": ["What is the riskiest assumption right now?", "What does the next 90 days need to prove?"],
     "checkin": ["Which experiment ran?", "What did the evidence say?", "What is the next milestone?"]},
    {"key": "financial_behavior", "group": "career", "label": "Financial behaviour coaching",
     "offering": "Budgeting habits, spending awareness, savings routines and money goals",
     "must_have": "Behaviour loop with strong privacy and no individualised regulated advice",
     "inputs": ["Income band", "Fixed costs", "Goals", "Spending categories", "Debt context"],
     "outputs": ["Spending reflection", "Budget scenarios", "Savings actions", "Alerts", "Referral prompts"],
     "approaches": ["motivational_interviewing", "accountability", "cognitive_behavioural"],
     "models": ["habit_loop", "smart", "check_in_scales"],
     "exclusions": ["Investment, tax, lending or insurance recommendations", "Outcome promises"],
     "escalation": ["Regulated financial adviser", "Debt advice service"],
     "intake": ["What money habit do you want to change?", "What is the goal you are saving toward?"],
     "checkin": ["Which spend surprised you?", "Did the savings action happen?", "Confidence 1-10"]},

    # ---------------- health ----------------
    {"key": "health_wellness", "group": "health", "label": "Health and wellness coaching",
     "offering": "Self-directed lifestyle change alongside the client's healthcare plan",
     "must_have": "Goal and accountability loop with scope guardrails and referral escalation",
     "inputs": ["Self-defined goal", "Readiness", "Routine", "Barriers", "Preferences", "Clinician instructions if shared"],
     "outputs": ["Action plan", "Habit support", "Progress reflection", "Evidence-based resources", "Referral prompts"],
     "approaches": ["motivational_interviewing", "person_centered", "accountability"],
     "models": ["grow", "habit_loop", "check_in_scales"],
     "exclusions": ["Diagnosis", "Interpreting medical data", "Prescribing or de-prescribing", "Supplement advice", "Meal plans", "Therapy"],
     "escalation": ["GP or treating clinician", "Registered dietitian", "Therapist"],
     "intake": ["What health change matters most to you right now?", "What has your clinician advised?", "Readiness 1-10"],
     "checkin": ["What did you manage this week?", "What got in the way?", "Energy 1-10", "Any new symptoms to raise with your clinician?"]},
    {"key": "behavior_change", "group": "health", "label": "Behaviour-change coaching",
     "offering": "Support for starting, stopping or sustaining a behaviour",
     "must_have": "Readiness-aware intervention selection rather than generic reminders",
     "inputs": ["Desired behaviour", "Readiness", "Confidence", "Barriers", "Triggers", "Prior attempts"],
     "outputs": ["Tiny action", "Implementation intention", "Coping plan", "Lapse recovery", "Review"],
     "approaches": ["motivational_interviewing", "cognitive_behavioural", "accountability"],
     "models": ["woop", "habit_loop", "implementation_intention"],
     "exclusions": ["Addiction treatment", "Medication changes"],
     "escalation": ["Addiction service", "Clinician"],
     "intake": ["Which behaviour, how often, starting when?", "Readiness 1-10", "Confidence 1-10"],
     "checkin": ["Days completed", "Which trigger caused a miss?", "What is the smaller version?"]},
    {"key": "nutrition_behavior", "group": "health", "label": "Nutrition behaviour coaching",
     "offering": "Meal-planning habits, grocery routines, mindful eating and adherence to professional guidance",
     "must_have": "Preference and context aware planning without diagnosing or prescribing",
     "inputs": ["Allergies", "Cultural foods", "Budget", "Schedule", "Cooking access", "Clinician restrictions"],
     "outputs": ["Grocery ideas", "Meal-prep routines", "Prompts", "Adherence reflection", "Dietitian referral"],
     "approaches": ["motivational_interviewing", "accountability"],
     "models": ["habit_loop", "implementation_intention"],
     "exclusions": ["Prescriptive meal plans", "Macro prescriptions for clinical conditions", "Supplement advice", "Eating-disorder treatment"],
     "escalation": ["Registered dietitian", "Eating-disorder service"],
     "intake": ["Which eating routine do you want to make easier?", "Any allergies or clinician restrictions?"],
     "checkin": ["Which routine held?", "Where did it break?", "How did you feel about food this week?"]},
    {"key": "fitness_movement", "group": "health", "label": "Fitness and movement coaching",
     "offering": "Motivation, consistency and routine support around movement",
     "must_have": "Adaptive progression with contraindication and referral checks",
     "inputs": ["Current activity", "Goals", "Equipment", "Access", "Preferences", "Limitations"],
     "outputs": ["Session suggestions", "Consistency tracking", "Recovery prompts", "Escalation on symptoms"],
     "approaches": ["accountability", "strengths_based", "somatic"],
     "models": ["smart", "habit_loop", "after_action_review"],
     "exclusions": ["Rehabilitation prescription", "Training through pain or red-flag symptoms"],
     "escalation": ["Physiotherapist", "Clinician"],
     "intake": ["What movement do you enjoy enough to repeat?", "Any injuries or clinician guidance?", "Days per week available"],
     "checkin": ["Sessions completed", "Perceived effort 1-10", "Any pain or symptoms?", "Recovery quality"]},
    {"key": "sleep", "group": "health", "label": "Sleep coaching",
     "offering": "Behavioural support for sleep routines and sleep environment",
     "must_have": "Sleep diary plus pattern-based behavioural experiments",
     "inputs": ["Schedule", "Sleep timing", "Environment", "Caffeine and alcohol", "Screen habits", "Symptoms"],
     "outputs": ["Wind-down plan", "Experiment", "Diary trend", "Clinician referral on red flags"],
     "approaches": ["cognitive_behavioural", "mindfulness_informed", "accountability"],
     "models": ["habit_loop", "check_in_scales", "implementation_intention"],
     "exclusions": ["Insomnia or apnoea treatment", "Sleep-medication advice"],
     "escalation": ["Sleep clinic", "GP"],
     "intake": ["Typical bedtime and wake time", "What disturbs your sleep most?", "Any breathing or severe symptoms?"],
     "checkin": ["Average hours", "Wind-down followed?", "Sleep quality 1-10", "One change for next week"]},
    {"key": "stress_management", "group": "health", "label": "Stress-management coaching",
     "offering": "Short interventions plus workload and recovery planning",
     "must_have": "Fast check-in that routes to the right intensity of support",
     "inputs": ["Stress rating", "Trigger", "Body cues", "Time available", "Preferred technique"],
     "outputs": ["Breathing or grounding practice", "Boundary action", "Recovery plan", "Escalation prompt"],
     "approaches": ["mindfulness_informed", "trauma_informed", "somatic"],
     "models": ["check_in_scales", "implementation_intention"],
     "exclusions": ["Anxiety or PTSD treatment"],
     "escalation": ["Therapist", "Crisis line"],
     "intake": ["What is driving the pressure right now?", "What has helped before?"],
     "checkin": ["Stress 1-10", "Which practice did you use?", "What boundary do you need next?"]},
    {"key": "mindfulness", "group": "health", "label": "Mindfulness and meditation coaching",
     "offering": "Sequenced practice, reflection and habit formation",
     "must_have": "Guided practice library with progression and personalisation",
     "inputs": ["Experience level", "Duration", "Style", "Sensory preferences", "Goals"],
     "outputs": ["Guided practice", "Brief reflection", "Consistency view", "Next practice"],
     "approaches": ["mindfulness_informed", "act_informed"],
     "models": ["habit_loop", "check_in_scales"],
     "exclusions": ["Treatment for trauma or dissociation"],
     "escalation": ["Trauma-trained clinician"],
     "intake": ["How long can you practise daily?", "Guided or silent?", "Anything to avoid?"],
     "checkin": ["Sessions completed", "What did you notice?", "Calm 1-10"]},
    {"key": "sport_performance", "group": "health", "label": "Sport and performance coaching",
     "offering": "Goal setting, practice review, competition preparation and recovery habits",
     "must_have": "Performance journal linking training, context and perceived execution",
     "inputs": ["Sport", "Position or event", "Level", "Competition calendar", "Metrics", "Coach instructions"],
     "outputs": ["Practice plan", "Pre-performance routine", "Review template", "Confidence and consistency trends"],
     "approaches": ["strengths_based", "accountability", "mindfulness_informed"],
     "models": ["after_action_review", "smart", "implementation_intention"],
     "exclusions": ["Injury rehabilitation", "Return-to-play clearance"],
     "escalation": ["Physiotherapist", "Sports physician", "Technical coach"],
     "intake": ["Next competition and target", "Which skill limits you?", "Weekly training load"],
     "checkin": ["Sessions completed", "Execution 1-10", "What did the review reveal?", "Recovery status"]},
    {"key": "recovery_habit", "group": "health", "label": "Recovery and habit-maintenance coaching",
     "offering": "Support after a lapse, burnout or disrupted routine",
     "must_have": "Non-judgemental lapse-recovery flow that restarts at the smallest viable step",
     "inputs": ["Previous routine", "Lapse context", "Current capacity", "Supports", "Risk signals"],
     "outputs": ["Restart plan", "Barrier adjustment", "Accountability check", "Referral if indicated"],
     "approaches": ["motivational_interviewing", "trauma_informed", "accountability"],
     "models": ["woop", "check_in_scales"],
     "exclusions": ["Relapse treatment for substance dependence", "Burnout diagnosis"],
     "escalation": ["Clinician", "Occupational health", "Addiction service"],
     "intake": ["What was working before?", "What changed?", "Capacity 1-10"],
     "checkin": ["Smallest step done?", "What barrier was removed?", "Capacity 1-10"]},

    # ---------------- relationships ----------------
    {"key": "relationship", "group": "relationships", "label": "Relationship coaching",
     "offering": "Communication, expectations, repair, boundaries and shared goals",
     "must_have": "Two-perspective conversation preparation without taking sides",
     "inputs": ["Relationship type", "Issue", "Desired outcome", "Safety screen", "Communication preferences"],
     "outputs": ["Conversation script", "Listening prompts", "Repair steps", "Boundary language", "Referral"],
     "approaches": ["person_centered", "systems", "trauma_informed"],
     "models": ["clear", "grow"],
     "exclusions": ["Couples therapy", "Mediating abuse", "Legal advice"],
     "escalation": ["Couples therapist", "Domestic-abuse service", "Solicitor"],
     "intake": ["What conversation keeps going wrong?", "What outcome would feel good for both of you?", "Do you feel safe in this relationship?"],
     "checkin": ["Which conversation happened?", "What went better?", "What still needs repair?"]},
    {"key": "dating", "group": "relationships", "label": "Dating coaching",
     "offering": "Values clarification, profile and story refinement, communication and reflection",
     "must_have": "Consent and safety aware scenario coaching",
     "inputs": ["Dating goals", "Identity", "Boundaries", "Preferences", "Platform", "Comfort level"],
     "outputs": ["Profile edits", "Message drafts", "Date reflection", "Safety checklist", "Pacing plan"],
     "approaches": ["person_centered", "strengths_based"],
     "models": ["values_sort", "after_action_review"],
     "exclusions": ["Manipulation or pick-up tactics", "Deceptive profiles"],
     "escalation": ["Therapist", "Safety service"],
     "intake": ["What are you actually looking for?", "Which boundaries are non-negotiable?"],
     "checkin": ["What did you notice on the last date?", "What will you do differently?"]},
    {"key": "marriage", "group": "relationships", "label": "Marriage and partnership coaching",
     "offering": "Shared planning and recurring relationship check-ins",
     "must_have": "Joint goals with a structured repair workflow",
     "inputs": ["Shared priorities", "Conflict patterns", "Time", "Consent of both parties", "Privacy settings"],
     "outputs": ["Weekly check-in", "Agenda", "Agreements", "Appreciation practice", "Referral"],
     "approaches": ["systems", "person_centered", "trauma_informed"],
     "models": ["clear", "oskar"],
     "exclusions": ["Therapy for entrenched distress", "Separation legal advice"],
     "escalation": ["Couples therapist", "Family solicitor"],
     "intake": ["What do you both want more of?", "Which recurring argument needs a new pattern?", "Is both partners' consent in place?"],
     "checkin": ["Did the check-in happen?", "Which agreement held?", "One appreciation each"]},
    {"key": "parenting", "group": "relationships", "label": "Parenting coaching",
     "offering": "Age-appropriate routines, communication and caregiver self-management",
     "must_have": "Child-development and safety aware scenario branching",
     "inputs": ["Child age", "Family context", "Routine", "Challenge", "Caregiver capacity", "Cultural values"],
     "outputs": ["Situation plan", "Scripts", "Routine cards", "Reflection", "Referral prompts"],
     "approaches": ["person_centered", "systems", "trauma_informed"],
     "models": ["grow", "habit_loop"],
     "exclusions": ["Child diagnosis", "Medical advice", "Safeguarding decisions"],
     "escalation": ["Paediatrician", "Child mental-health service", "Safeguarding authority"],
     "intake": ["Child's age and the situation", "What have you already tried?", "What does calm look like in your home?"],
     "checkin": ["Which routine helped?", "Where did it escalate?", "Caregiver capacity 1-10"]},
    {"key": "family", "group": "relationships", "label": "Family coaching",
     "offering": "Roles, expectations, transitions, caregiving and household coordination",
     "must_have": "Multi-party consent and access control",
     "inputs": ["Participants", "Roles", "Shared goals", "Sensitive topics", "Guardian permissions"],
     "outputs": ["Family agreements", "Meeting agenda", "Action ownership", "Aggregate progress"],
     "approaches": ["systems", "person_centered"],
     "models": ["clear", "oskar"],
     "exclusions": ["Family therapy", "Custody or legal advice"],
     "escalation": ["Family therapist", "Solicitor", "Social services"],
     "intake": ["Who is involved and who consented?", "What does the family need to decide?"],
     "checkin": ["Was the family meeting held?", "Which actions had owners?", "What is unresolved?"]},
    {"key": "social_confidence", "group": "relationships", "label": "Social-confidence coaching",
     "offering": "Practice for initiating, joining and sustaining social interactions",
     "must_have": "Graduated exposure with a post-event learning loop",
     "inputs": ["Context", "Anxiety and confidence rating", "Desired behaviour", "Safety boundaries", "Support person"],
     "outputs": ["Micro-challenge", "Script", "Reflection", "Next-step ladder"],
     "approaches": ["cognitive_behavioural", "trauma_informed", "strengths_based"],
     "models": ["check_in_scales", "implementation_intention"],
     "exclusions": ["Social anxiety disorder treatment"],
     "escalation": ["Therapist"],
     "intake": ["Which social situation do you avoid?", "What would a small win look like?"],
     "checkin": ["Which challenge did you try?", "Anxiety before and after 1-10", "Next rung on the ladder"]},
    {"key": "conflict", "group": "relationships", "label": "Conflict coaching",
     "offering": "Preparation for a specific dispute, without acting as a mediator",
     "must_have": "Interests and needs map plus de-escalation guardrails",
     "inputs": ["Parties", "Facts", "Interests", "Power imbalance", "Desired outcome", "Safety concerns"],
     "outputs": ["Neutral opening", "Questions", "Options", "Boundary plan", "Referral"],
     "approaches": ["systems", "trauma_informed", "person_centered"],
     "models": ["fuel", "pre_mortem"],
     "exclusions": ["Legal advice", "Formal mediation", "Coaching both sides of the same dispute"],
     "escalation": ["Accredited mediator", "Solicitor", "HR"],
     "intake": ["Who is the dispute with and what is at stake?", "What would resolution look like?", "Any safety concerns?"],
     "checkin": ["What was said?", "What de-escalated it?", "Next step or referral"]},

    # ---------------- specialised ----------------
    {"key": "values_based", "group": "specialized", "label": "Values-based coaching",
     "offering": "Decisions and habits anchored in personally chosen principles",
     "must_have": "Values-to-action traceability",
     "inputs": ["Values ranking", "Conflicts", "Contexts", "Non-negotiables", "Examples"],
     "outputs": ["Alignment check", "Trade-off prompts", "Action experiment", "Reflection"],
     "approaches": ["act_informed", "narrative", "person_centered"],
     "models": ["values_sort", "grow"],
     "exclusions": ["Imposing the coach's values"],
     "escalation": ["Therapist for value-based distress"],
     "intake": ["Name your top five values", "Where do they conflict?"],
     "checkin": ["Which action matched your values?", "Which did not, and why?"]},
    {"key": "spiritual", "group": "specialized", "label": "Spiritual or faith-sensitive coaching",
     "offering": "Meaning, practices, discernment and life integration",
     "must_have": "Client-controlled worldview and language settings",
     "inputs": ["Tradition or secular stance", "Practices", "Boundaries", "Community", "Open questions"],
     "outputs": ["Reflection", "Practice plan", "Discernment journal", "Referral to chosen clergy or mentor"],
     "approaches": ["person_centered", "narrative", "mindfulness_informed"],
     "models": ["values_sort", "check_in_scales"],
     "exclusions": ["Doctrinal authority", "Proselytising", "Therapy"],
     "escalation": ["Chosen faith leader", "Therapist"],
     "intake": ["What language and tradition should I use or avoid?", "What are you discerning?"],
     "checkin": ["Which practice held?", "What became clearer?"]},
    {"key": "dei_belonging", "group": "specialized", "label": "Inclusion and belonging coaching",
     "offering": "Workplace or community belonging, bias awareness, allyship and identity-safe growth",
     "must_have": "Context-aware prompts that do not individualise structural problems",
     "inputs": ["Identity and disclosure preferences", "Organisational context", "Power dynamics", "Goals"],
     "outputs": ["Conversation plan", "Allyship actions", "Policy and resource links", "Aggregate insights only"],
     "approaches": ["systems", "person_centered", "trauma_informed"],
     "models": ["clear", "fuel"],
     "exclusions": ["Legal claims advice", "Exposing identity data", "Blaming the individual for structural issues"],
     "escalation": ["HR", "Employment solicitor", "Advocacy organisation"],
     "intake": ["What would belonging look like here?", "What do you want kept private?"],
     "checkin": ["Which action did you take?", "What did the system do in response?"]},
    {"key": "neurodiversity", "group": "specialized", "label": "Neurodiversity-affirming coaching",
     "offering": "Executive-function support and self-advocacy adapted to the individual",
     "must_have": "Highly configurable sensory, cognitive and communication experience",
     "inputs": ["Attention patterns", "Sensory preferences", "Task-initiation barriers", "Communication needs"],
     "outputs": ["Low-friction routines", "Visual plans", "Scripts", "Energy-aware scheduling", "Referral"],
     "approaches": ["strengths_based", "person_centered", "trauma_informed"],
     "models": ["implementation_intention", "habit_loop", "check_in_scales"],
     "exclusions": ["Assessment or diagnosis", "Medication advice"],
     "escalation": ["Diagnostic service", "Occupational therapist"],
     "intake": ["What environment helps you think?", "What drains you fastest?", "How should I communicate with you?"],
     "checkin": ["Which routine worked?", "Which had too much friction?", "Energy 1-10"]},
    {"key": "adhd_executive", "group": "specialized", "label": "ADHD and executive-function coaching",
     "offering": "Task initiation, working memory support, environment design and follow-through",
     "must_have": "Friction-aware task decomposition with an immediate next action",
     "inputs": ["Task", "Deadline", "Estimated effort", "Distractions", "Preferred reminders"],
     "outputs": ["One-step plan", "Timer", "Body-doubling option", "Reset flow", "Progress evidence"],
     "approaches": ["strengths_based", "accountability", "person_centered"],
     "models": ["implementation_intention", "check_in_scales"],
     "exclusions": ["Diagnosis", "Medication advice"],
     "escalation": ["Diagnostic service", "Prescribing clinician"],
     "intake": ["What are you avoiding starting?", "What reminder style actually works for you?"],
     "checkin": ["What got started?", "Which reset did you need?", "Focus 1-10"]},
    {"key": "chronic_illness", "group": "specialized", "label": "Chronic-illness self-management coaching",
     "offering": "Support for routines and self-management under professional care",
     "must_have": "Clinician-plan alignment and symptom-sensitive pacing",
     "inputs": ["Self-defined goals", "Care-plan instructions", "Fatigue", "Symptoms", "Appointments", "Supports"],
     "outputs": ["Routine plan", "Questions for the clinician", "Pacing reflection", "Red-flag referral"],
     "approaches": ["person_centered", "motivational_interviewing", "trauma_informed"],
     "models": ["check_in_scales", "habit_loop"],
     "exclusions": ["Diagnosis", "Interpreting results", "Changing prescribed treatment"],
     "escalation": ["Treating clinician", "Specialist nurse", "Emergency services on red flags"],
     "intake": ["What has your care team advised?", "What would an easier week look like?", "What are your red-flag symptoms?"],
     "checkin": ["Pacing held?", "Symptom load 1-10", "Questions for your next appointment"]},
    {"key": "caregiver", "group": "specialized", "label": "Caregiver coaching",
     "offering": "Capacity, boundaries, coordination and sustainable caregiving routines",
     "must_have": "Caregiver-load check plus resource navigation",
     "inputs": ["Care recipient needs", "Tasks", "Support network", "Respite options", "Urgency"],
     "outputs": ["Delegation plan", "Respite actions", "Care meeting agenda", "Resource and referral list"],
     "approaches": ["person_centered", "systems", "trauma_informed"],
     "models": ["check_in_scales", "grow"],
     "exclusions": ["Medical decisions for the care recipient", "Legal or benefits advice"],
     "escalation": ["Social care", "Carer support organisation", "Clinician"],
     "intake": ["What are you carrying week to week?", "Where could someone else step in?"],
     "checkin": ["Load 1-10", "What did you delegate?", "Did you get any respite?"]},
    {"key": "grief_loss", "group": "specialized", "label": "Grief and loss support coaching",
     "offering": "Non-clinical companionship, stabilisation, meaning-making and practical support",
     "must_have": "Sensitive check-ins with risk escalation and no forced stages",
     "inputs": ["Loss context", "Current needs", "Rituals", "Support", "Safety signals"],
     "outputs": ["Gentle prompt", "Practical next step", "Remembrance practice", "Human or clinical referral"],
     "approaches": ["trauma_informed", "person_centered", "narrative"],
     "models": ["check_in_scales"],
     "exclusions": ["Grief therapy", "Prolonged-grief treatment", "Timelines for grieving"],
     "escalation": ["Bereavement service", "Therapist", "Crisis line"],
     "intake": ["What would support look like today?", "What do you not want to talk about?"],
     "checkin": ["How is today, in one sentence?", "What practical thing would help?", "Do you feel safe?"]},
    {"key": "relocation_expat", "group": "specialized", "label": "Relocation and expatriate coaching",
     "offering": "Practical adaptation, belonging, identity and routines in a new place",
     "must_have": "Local-context checklist plus a social integration plan",
     "inputs": ["Destination", "Language", "Administrative needs", "Culture", "Support network", "Timeline"],
     "outputs": ["First-30-days plan", "Questions list", "Connection experiments", "Resource links"],
     "approaches": ["person_centered", "systems", "solution_focused"],
     "models": ["grow", "implementation_intention"],
     "exclusions": ["Immigration, tax or legal advice"],
     "escalation": ["Immigration adviser", "Relocation service"],
     "intake": ["Where are you moving and when?", "What has to be sorted first?", "How do you make friends best?"],
     "checkin": ["Which admin task closed?", "Which connection did you make?", "Settled 1-10"]},
]

DELIVERY = [
    {"key": "one_time", "label": "One-time session", "use": "A decision, interview, difficult conversation or immediate plan"},
    {"key": "sprint", "label": "Two to four week sprint", "use": "A narrow behaviour or skill change"},
    {"key": "program", "label": "Six to twelve week programme", "use": "A multi-step outcome needing practice and review"},
    {"key": "membership", "label": "Ongoing membership", "use": "Multiple goals, maintenance and recurring check-ins"},
    {"key": "human_plus_ai", "label": "Human plus assistant", "use": "Sensitive or high-stakes work with coach review"},
    {"key": "group", "label": "Group or team programme", "use": "Shared goals and peer learning"},
    {"key": "sponsored", "label": "Sponsored workplace offering", "use": "Employer-funded with strict privacy boundaries"},
]

DIRECTIVENESS = [
    {"key": "listen", "label": "Just listen", "note": "Reflect and summarise, no advice"},
    {"key": "explore", "label": "Help me explore", "note": "Questions first, options only on request"},
    {"key": "permission_based", "label": "Ask before advising", "note": "Default: permission before suggestions"},
    {"key": "options", "label": "Give me options", "note": "Offer choices with trade-offs"},
    {"key": "plan", "label": "Make me a plan", "note": "Direct, action-first"},
]

DOMAIN_BY_KEY = {d["key"]: d for d in DOMAINS}
GROUP_BY_KEY = {g["key"]: g for g in GROUPS}
APPROACH_BY_KEY = {a["key"]: a for a in APPROACHES}
MODEL_BY_KEY = {m["key"]: m for m in SESSION_MODELS}
